name: 🐛 Bug Report
description: File a bug report to help us improve Quick Docs
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe what the bug is...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Android
        - iOS
        - Web
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: OS Version
      description: Version of your operating system (e.g., Android 13, iOS 17.0)
      placeholder: e.g., Android 13, iOS 17.0
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the application is affected?
      options:
        - Frontend (Flutter App)
        - Backend (FastAPI)
        - Firebase/Authentication
        - File Upload/Processing
        - Search Functionality
        - UI/UX
        - Other
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: App Version
      description: Version of the app (if applicable)
      placeholder: e.g., 1.0.0
    validations:
      required: false

  - type: input
    id: flutter_version
    attributes:
      label: Flutter Version
      description: Flutter version (for frontend issues)
      placeholder: e.g., 3.16.0
    validations:
      required: false

  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: Python version (for backend issues)
      placeholder: e.g., 3.11.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error logs / Stack trace
      description: If applicable, add any error messages or stack traces
      render: shell
      placeholder: Paste error logs or stack trace here...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can drag and drop images here.
      placeholder: Add screenshots here...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...


