name: ✨ Feature Request
description: Suggest a new feature or enhancement for Quick Docs
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your needs.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternative approaches I've thought about...
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area of the application would this feature affect?
      options:
        - Frontend (Flutter App)
        - Backend (FastAPI)
        - File Upload/Processing
        - Search Functionality
        - Organization (Folders/Tags)
        - Authentication
        - UI/UX
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my workflow
    validations:
      required: false

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: Describe your use case - when and why would you use this feature?
      placeholder: I would use this feature when...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Screenshots
      description: If applicable, add mockups, wireframes, or screenshots to help visualize your feature request. You can drag and drop images here.
      placeholder: Add mockups or screenshots here...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, references, or examples about the feature request here.
      placeholder: Any additional information that might be helpful...

